<?php

return array(
    'default'     => 'fms',
    'connections' => array(
        'ams' => array(
            'driver'    => 'mysql',
            'host'      => 'localhost',
            'database'  => 'AMS',
            'username'  => 'root',
            'password'  => '',
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
        ),
        'qauth' => array(
            'driver'    => 'mysql',
            'host'      => '10.10.10.121',
            'database'  => 'QAuth',
            'username'  => 'root',
            'password'  => 'bamburuncingqeon',
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
        ),
        'fms' => array(
            'driver'    => 'mysql',
            'host'      => '10.10.10.219',
            'database'  => 'fms',
            'username'  => 'root',
            'password'  => 'bamburuncingqeon',
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
        ),
        'api' => array(
            'driver'    => 'mysql',
            'host'      => 'localhost',
            'database'  => 'QData',
            'username'  => 'root',
            'password'  => '',
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
        ),
        'session' => array(
            'driver'    => 'mysql',
            'host'      => '10.10.20.19',
            'database'  => 'QSession',
            'port'      => '3224',
            'username'  => 'webusr',
            'password'  => 'WYWaNDGDLZmmEXe9',
            'charset'   => 'utf8',
            'collation' => 'utf8_general_ci',
            'prefix'    => '',
        ),
    ),
);
